# Generated by Django 4.1.1 on 2022-09-18 10:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('usr_id', models.IntegerField(editable=False, primary_key=True, serialize=False)),
                ('usr_fio', models.CharField(max_length=128)),
                ('usr_sex', models.CharField(choices=[('m', 'male'), ('f', 'female')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usr_contact', models.CharField(max_length=128, unique=True)),
                ('usr_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees_app.users')),
            ],
        ),
    ]
