# Generated by Django 4.1.1 on 2022-09-18 10:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employees_app', '0002_posts'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='usr_post',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='employees_app.posts'),
        ),
    ]
