# Generated by Django 4.1.1 on 2022-09-18 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees_app', '0003_users_usr_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='Departments',
            fields=[
                ('dep_id', models.IntegerField(editable=False, primary_key=True, serialize=False)),
                ('dep_code', models.CharField(max_length=128, unique=True)),
                ('dep_description', models.CharField(max_length=256)),
            ],
        ),
        migrations.AlterField(
            model_name='posts',
            name='post_id',
            field=models.IntegerField(editable=False, primary_key=True, serialize=False),
        ),
    ]
