# Generated by Django 4.1.1 on 2022-09-18 11:11

from django.db import migrations, models
import django.db.models.deletion
import employees_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('employees_app', '0004_departments_alter_posts_post_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departments',
            name='dep_code',
            field=models.CharField(max_length=128, unique=True, validators=[employees_app.models.Departments.validate_dep_code]),
        ),
        migrations.CreateModel(
            name='Usr_Dep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dep_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees_app.departments')),
                ('usr_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees_app.users')),
            ],
        ),
    ]
