# Generated by Django 4.1.1 on 2022-09-18 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees_app', '0009_dep_director_date_of_transition'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dep_director',
            name='date_of_transition',
        ),
        migrations.AddField(
            model_name='usr_dep',
            name='date_of_transition',
            field=models.DateField(auto_now=True),
        ),
    ]
