# Generated by Django 4.1.1 on 2022-09-18 11:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employees_app', '0010_remove_dep_director_date_of_transition_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usr_dep',
            name='date_of_transition',
            field=models.DateField(),
        ),
        migrations.CreateModel(
            name='Emp_Chef',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chef_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Chef_name', to='employees_app.users')),
                ('usr_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='Emp_id', to='employees_app.users')),
            ],
        ),
    ]
