# Generated by Django 4.1.1 on 2022-09-18 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees_app', '0012_departments_dep_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departments',
            name='dep_status',
            field=models.CharField(choices=[('active', 'active'), ('inactive', 'inactive')], default='active', max_length=128),
        ),
    ]
