# Generated by Django 4.1.1 on 2022-09-22 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees_app', '0014_remove_contacts_id_remove_emp_chef_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacts',
            name='contact_id',
            field=models.AutoField(editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='departments',
            name='dep_id',
            field=models.AutoField(editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='posts',
            name='post_id',
            field=models.AutoField(editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='users',
            name='usr_id',
            field=models.AutoField(editable=False, primary_key=True, serialize=False),
        ),
    ]
