# Generated by Django 4.1.1 on 2022-09-22 20:10

from django.db import migrations, models
import employees_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('employees_app', '0015_alter_contacts_contact_id_alter_departments_dep_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departments',
            name='dep_code',
            field=models.CharField(max_length=10, unique=True, validators=[employees_app.models.Departments.validate_dep_code]),
        ),
    ]
