# Generated by Django 4.1.1 on 2022-09-22 20:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employees_app', '0016_alter_departments_dep_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contacts',
            old_name='contact_id',
            new_name='contact',
        ),
        migrations.RenameField(
            model_name='contacts',
            old_name='usr_id',
            new_name='usr',
        ),
        migrations.RenameField(
            model_name='dep_director',
            old_name='dep_id',
            new_name='dep',
        ),
        migrations.RenameField(
            model_name='dep_director',
            old_name='dir_id',
            new_name='dir',
        ),
        migrations.RenameField(
            model_name='departments',
            old_name='dep_id',
            new_name='dep',
        ),
        migrations.RenameField(
            model_name='emp_chef',
            old_name='chef_id',
            new_name='chef',
        ),
        migrations.RenameField(
            model_name='posts',
            old_name='post_id',
            new_name='post',
        ),
        migrations.RenameField(
            model_name='users',
            old_name='usr_id',
            new_name='usr',
        ),
        migrations.RenameField(
            model_name='usr_dep',
            old_name='dep_id',
            new_name='dep',
        ),
        migrations.RenameField(
            model_name='usr_dep',
            old_name='usr_id',
            new_name='usr',
        ),
        migrations.RemoveField(
            model_name='emp_chef',
            name='usr_id',
        ),
        migrations.AddField(
            model_name='emp_chef',
            name='usr',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='Emp', serialize=False, to='employees_app.users'),
            preserve_default=False,
        ),
    ]
