# Generated by Django 4.1.1 on 2022-09-29 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees_app', '0017_rename_contact_id_contacts_contact_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Posts',
            new_name='Positions',
        ),
        migrations.RenameField(
            model_name='positions',
            old_name='post',
            new_name='position',
        ),
        migrations.RenameField(
            model_name='positions',
            old_name='post_descr',
            new_name='position_descr',
        ),
        migrations.RenameField(
            model_name='users',
            old_name='usr_post',
            new_name='usr_position',
        ),
        migrations.AlterField(
            model_name='usr_dep',
            name='date_of_transition',
            field=models.DateField(auto_now_add=True),
        ),
    ]
