# Generated by Django 4.1.1 on 2022-09-29 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees_app', '0018_rename_posts_positions_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='positions',
            old_name='position_descr',
            new_name='description',
        ),
    ]
