# Generated by Django 4.1.1 on 2022-09-29 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees_app', '0019_rename_position_descr_positions_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='usr',
            new_name='user',
        ),
    ]
